name: Deploy Telegram Bot WebApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run setup script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.6789490938:AAFkhwkeeqrsyBTzE0I6uKAiKCSz0qjMWWs}}
          GITHUB_USERNAME: ${{ secrets.duccodedao }}
          GITHUB_REPO: ${{ secrets.telegram-bot-deploy }}
        run: node setup.js
